name: Deploy to prod

on:
  push:
    branches:
      - main

jobs:
  deploy_server:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1

    steps:
    - name: "checkout repo"
      uses: actions/checkout@v2

    - name: "gcloud setup"
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: spliceai-lookup-361000
        service_account_key: ${{ secrets.GCP_DEPLOY_KEY }}

    - name: "build and deploy API server"
      run: |
          gcloud beta run deploy --project=spliceai-lookup-361000 --region=australia-southeast1 --service-account=spliceaiweb@spliceai-lookup-361000.iam.gserviceaccount.com --no-allow-unauthenticated --execution-environment=gen2 --source=SpliceAIWeb --set-env-vars=BUCKET=cpg-spliceai-lookup,MNT_DIR=/mnt/cpg-spliceai-lookup,HG38=/mnt/cpg-spliceai-lookup/Homo_sapiens_assembly38.fasta spliceaiweb

    - name: "build and deploy web UI"
      run: |
          gcloud beta run deploy --project=spliceai-lookup-361000 --region=australia-southeast1 --service-account=spliceaiui@spliceai-lookup-361000.iam.gserviceaccount.com --no-allow-unauthenticated --execution-environment=gen2 --source=spliceaiui spliceaiui
